#!/data/data/com.termux/files/usr/bin/bash

unset LD_PRELOAD
export JAVA_HOME="$PREFIX/share/jdk8"

export LIB_DIR="$PREFIX/share/glib"
export LD_LIBRARY_PATH="$LIB_DIR"

exec $JAVA_HOME/bin/java "$@"

